import type { PopularMoviesResponse } from "../types/movies";

export const popularMovies: PopularMoviesResponse = {
  page: 1,
  results: [
    {
      id: 1,
      title: "The Shawshank Redemption",
      overview:
        "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      release_date: "1994-09-22",
      vote_average: 9.3,
      vote_count: 2345,
      poster_path: "/path/to/poster1.jpg",
      popularity: 98.7,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 2,
      title: "The Godfather",
      overview:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      release_date: "1972-03-24",
      vote_average: 9.2,
      vote_count: 1567,
      poster_path: "/path/to/poster2.jpg",
      popularity: 92.1,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 3,
      title: "The Dark Knight",
      overview:
        "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
      release_date: "2008-07-18",
      vote_average: 9.0,
      vote_count: 2300,
      poster_path: "/path/to/poster3.jpg",
      popularity: 100.5,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 4,
      title: "Pulp Fiction",
      overview:
        "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      release_date: "1994-10-14",
      vote_average: 8.9,
      vote_count: 1900,
      poster_path: "/path/to/poster4.jpg",
      popularity: 85.3,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 5,
      title: "Forrest Gump",
      overview:
        "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.",
      release_date: "1994-07-06",
      vote_average: 8.8,
      vote_count: 2100,
      poster_path: "/path/to/poster5.jpg",
      popularity: 88.2,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 6,
      title: "Inception",
      overview:
        "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      release_date: "2010-07-16",
      vote_average: 8.7,
      vote_count: 2200,
      poster_path: "/path/to/poster6.jpg",
      popularity: 95.4,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 7,
      title: "Fight Club",
      overview:
        "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
      release_date: "1999-10-15",
      vote_average: 8.8,
      vote_count: 1800,
      poster_path: "/path/to/poster7.jpg",
      popularity: 89.6,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 8,
      title: "The Matrix",
      overview:
        "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
      release_date: "1999-03-31",
      vote_average: 8.7,
      vote_count: 2000,
      poster_path: "/path/to/poster8.jpg",
      popularity: 90.3,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 9,
      title: "The Lord of the Rings: The Return of the King",
      overview:
        "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      release_date: "2003-12-17",
      vote_average: 8.9,
      vote_count: 2500,
      poster_path: "/path/to/poster9.jpg",
      popularity: 97.8,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
    {
      id: 10,
      title: "The Silence of the Lambs",
      overview:
        "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer, a madman who skins his victims.",
      release_date: "1991-02-14",
      vote_average: 8.6,
      vote_count: 1700,
      poster_path: "/path/to/poster10.jpg",
      popularity: 84.5,
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      original_language: "",
      original_title: "",
      video: false,
    },
  ],
};
